project:
  type: book
  output-dir: docs

date: today
date-format: long

from: markdown+emoji

book:
  title: "Statistical Computing using R and Python"
  author: "Susan Vanderplas"
  favicon: build_deps/favicon.ico
  cover-image: build_deps/cover.png
  site-url: https://srvanderplas.github.io/stat-computing-r-python/
  repo-url: https://github.com/srvanderplas/stat-computing-r-python/
  repo-branch: main
  repo-actions: [edit]
  page-navigation: true
  search: true
  sidebar:
    style: floating
    collapse-level: 3
  page-footer:
    left: "Copyright 2023, Susan Vanderplas"
    right:
      - icon: github
        href: https://github.com/srvanderplas
      - icon: twitter
        href: https://twitter.com/srvanderplas
  chapters:
    - index.qmd
    - how-to-use.qmd
    - part: part-tools/00-tools-intro.qmd
      chapters:
        - part-tools/01-computer-basics.qmd
        - part-tools/02-setting-up-computer.qmd
        - part-tools/03-scripts-notebooks.qmd
        - part-tools/04-Rstudio-interface.qmd
        - part-tools/05-git-and-github.qmd

    - part: part-gen-prog/00-gen-prog.qmd
      chapters:
        - part-gen-prog/01-basic-var-types.qmd
        - part-gen-prog/02-prog-functions.qmd
        - part-gen-prog/03-data-struct.qmd
        - part-gen-prog/04-control-struct.qmd
        - part-gen-prog/05-functions.qmd
        - part-gen-prog/06-matrix-calcs.qmd

    - part: part-wrangling/00-wrangling.qmd
      chapters:
        - part-wrangling/01-data-input.qmd
        - part-wrangling/02-basic-data-vis.qmd
        - part-wrangling/03-data-cleaning.qmd
        - part-wrangling/04-data-reshape.qmd
        - part-wrangling/05-data-join.qmd
        - part-wrangling/06-strings.qmd
        - part-wrangling/07-datetime.qmd
        - part-wrangling/08-functional-prog.qmd
        - part-wrangling/09-spatial-formats.qmd

    - graveyard.qmd

bibliography: references.bib
csl: build_deps/ieee-with-url.csl

format:
  html:
    css: build_deps/style.css
    theme: cosmo
    code-link: true
    include-in-header: "header.html"
    code-copy: true
  pdf:
    documentclass: scrreprt

# Knitr options
knitr:
  opts_chunk:
    collapse: true
    message: false
    warning: false
    error: true
    dpi: 300
    width: 60

execute:
  freeze: auto  # re-render only when source changes

