project:
  type: book
  output-dir: docs

date: today
date-format: long

from: markdown+emoji

book:
  title: "Statistical Computing using R and Python"
  author: "Susan Vanderplas"
  favicon: build_deps/favicon.ico
  cover-image: build_deps/cover.png
  site-url: https://srvanderplas.github.io/unl-stat850/
  repo-url: https://github.com/srvanderplas/unl-stat850/
  repo-branch: main
  repo-actions: [edit]
  page-navigation: true
  sidebar:
    style: floating
    collapse-level: 3
  search:
    location: navbar
  page-footer:
    left: "Copyright 2023, Susan Vanderplas"
    right:
      - icon: github
        href: https://github.com/srvanderplas
      - icon: twitter
        href: https://twitter.com/srvanderplas
  chapters:
    - index.qmd
    - how-to-use.qmd
    - part: part-tools/00-tools-intro.qmd
      chapters:
        - part-tools/01-computer-basics.qmd
        - part-tools/02-setting-up-computer.qmd

    - references.qmd

bibliography: references.bib
csl: build_deps/ieee-with-url.csl

format:
  html:
    css: style.css
    theme: cosmo
    code-link: true
    include-in-header: "header.html"
    code-copy: true
  pdf:
    documentclass: scrreprt

# Knitr options
knitr:
  opts_chunk:
    collapse: true
    message: false
    warning: false
    error: true
    dpi: 300
    width: 60

execute:
  freeze: auto  # re-render only when source changes

