project:
  type: book
  output-dir: docs
  preview:
    port: 3430
    browser: true

date: today
date-format: long

from: markdown+emoji

book:
  title: "Statistical Computing using R and Python"
  author: "Susan Vanderplas"
  issued: today
  favicon: build_deps/favicon.ico
  cover-image: build_deps/cover.png
  public-url: "https://srvanderplas.github.io/stat-computing-r-python/"
  site-url: "https://srvanderplas.github.io/stat-computing-r-python/"
  repo-url: "https://github.com/srvanderplas/stat-computing-r-python/"
  repo-branch: main
  repo-actions: [edit]
  page-navigation: true
  search: true
  google-analytics: "G-4ZFBDKXJXP"
  type: book
  medium: ebook
  sidebar:
    style: floating
    collapse-level: 3
  page-footer:
    left: "Copyright 2023, Susan Vanderplas"
    right:
      - icon: github
        href: "https://github.com/srvanderplas"
      - icon: twitter
        href: "https://twitter.com/srvanderplas"
  comments:
    giscus:
      repo: srvanderplas/stat-computing-r-python
      category: "General"
      mapping: "pathname"
  chapters:
    - index.qmd

    - part: part-tools/00-tools-intro.qmd
      chapters:
        - part-tools/01-computer-basics.qmd
        - part-tools/02-setting-up-computer.qmd
        - part-tools/03-scripts-notebooks.qmd
        - part-tools/04-Rstudio-interface.qmd
        - part-tools/05-git-and-github.qmd

    - part: part-gen-prog/00-gen-prog.qmd
      chapters:
        - part-gen-prog/00-intro.qmd
        - part-gen-prog/01-basic-var-types.qmd
        - part-gen-prog/02-prog-functions.qmd
        - part-gen-prog/03-data-struct.qmd
        - part-gen-prog/035-matrix-calcs.qmd
        - part-gen-prog/04-control-struct.qmd
        - part-gen-prog/05-functions.qmd
        - part-gen-prog/06-debugging.qmd
        - part-gen-prog/07-extra.qmd

    - part: part-wrangling/00-wrangling.qmd
      chapters:
        - part-wrangling/01-data-input.qmd
        - part-wrangling/02-basic-data-vis.qmd
        - part-wrangling/02a-eda.qmd
        - part-wrangling/02b-graphics.qmd
        - part-wrangling/02c-good-graphics.qmd
        - part-wrangling/03-data-cleaning.qmd
        - part-wrangling/04-strings.qmd
        - part-wrangling/05-data-reshape.qmd
        - part-wrangling/06-data-join.qmd
        - part-wrangling/07-datetime.qmd
        - part-wrangling/08-functional-prog.qmd
        - part-wrangling/09-spatial-formats.qmd

    # - part: "Advanced Topics"
    #   chapters:
    #     - part-advanced-topics/01-continuous-deployment.qmd
    #     - part-advanced-topics/02-data-doc.qmd
    #     - part-advanced-topics/03-databases.qmd
    #     - part-advanced-topics/04-web-tech.qmd
    #     - part-advanced-topics/05-advanced-markdown.qmd
    #     - part-advanced-topics/06-interactive-data.qmd
    #     - part-advanced-topics/07-software-engineering.qmd
    #     - part-advanced-topics/08-special-data.qmd

    - graveyard.qmd

bibliography:
  - references.bib
  - packages.bib
csl: build_deps/ieee-with-url.csl

format:
  html:
    css: build_deps/style.css
    theme: ['cosmo', build_deps/callouts.scss]
    code-link: true
    include-in-header: "build_deps/header.html"
    code-copy: true
  # pdf:
  #   documentclass: scrreprt
  #   include-in-header: "header.tex"

# Knitr options
knitr:
  opts_chunk:
    collapse: true
    message: false
    warning: false
    error: true
    dpi: 300
    width: 60

execute:
  freeze: auto  # re-render only when source changes

