name: Render and deploy Quarto files
on:
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
      GITHUB_PAT: ${{ secrets.GH_PAT }}

    steps:
    - uses: actions/checkout@v4

    - name: Change ownership of /github/home
      run: sudo chown -R $(whoami) /github/home

    - name: Install system dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install -y libudunits2-dev libgdal-dev
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y
      shell: /bin/bash {0}

    - name: Setup Python and virtual environment using requirements file
      id: setup-python-venv
      uses: srvanderplas/action-setup-venv@v1.1.3
      with:
        python-version-file: '.python-version'
        cache-dependency-path: requirements.txt
        install-cmd: "./py-deps -i"

    - name: Renv setup
      uses: r-lib/actions/setup-renv@v2

    - name: Renv and R install status
      shell: Rscript {0}
      run: |
        renv::status()
        renv::diagnostics()
        devtools::session_info()

    - name: Reticulate checks
      shell: Rscript {0}
      with:
        RETICULATE_PYTHON: ${{ setup-python-venv.reticulate-python }}
        RETICULATE_PYTHON_ENV: ${{ setup-python-venv.venv-path }}
      run: |
        reticulate::virtualenv_create('r-reticulate')
        reticulate::py_config()
        if(!"venv" %in% reticulate::virtualenv_list()) {
          reticulate::py_install(version = readLines(".python-version"))
          reticulate::virtualenv_create("$GITHUB_WORKSPACE/venv", requirements = "requirements.txt", python = readLines(".python-version"))
        } else {

        }
        reticulate::use_virtualenv("venv")

    - uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.5.57
        tinytex: true

    - name: Render Quarto Project
      shell: /bin/bash {0}
      run: |
        quarto render --execute-debug

    - name: "Deploy to gh-pages"
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
